<?php

/**
 * @file
 * Code for the Bibliobird forum feature.
 */

include_once 'bibliobird_forum.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Sets a default subject for comments on the forum - it's the parent comment or node title plus 'Re: '.
 */
function bibliobird_forum_form_comment_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  if ($node->type == 'forum' && empty($form['cid']['#value'])) {
    if (!empty($form['pid']['#value'])) {
      $parent = comment_load($form['pid']['#value']);
      $parent_title = $parent->subject;
    }
    else {
      $parent_title = $node->title;
    }

    $re = t('Re: ');
    $re_len = drupal_strlen($re);
    if (drupal_substr($parent_title, 0, $re_len) == $re) {
      $subject = $parent_title;
    }
    else {
      $subject = $re . $parent_title;
    }

    $size = isset($form['subject']['#size']) ? $form['subject']['size'] : 64;
    $form['subject']['#default_value'] = drupal_substr($subject, 0, $size);
  }
}

